# Name: Auto Subs
# Description: Automatically turn on subtitles when all strings in the list are matched against a subtitle track
enabled=yes
# Match pattern, all values must match from comma separated list {(tag)text}
match=en,forced