enabled=yes
# Number of thumbnails to generate {int(100-400)}
#thumbnail_count=150
# Thumbnail height as a percentage of the uosc timeline height {int(20-100)}
#thumbnail_height_percent=80
# Animation durationg (ms) {int(100-1000)}
#animation_duration=100
# Animation fps {int}
#animation_fps=30
# Hide filmstript timeout (ms) {int(0-1000)}
#idle_timeout=0
# Generate thumbnails concurrently {int(1-12)}
#max_concurrent=4
#hwdec=auto
# Process priority {select:idle|low|normal|high}
#process_priority=normal
#overlay_id=10
#mpv_path=mpv
#temp_dir=%TEMP%