# UNCOMMENT AND SET enabled=no to disable this plugin
#enabled=yes
# path to subliminal, should be in your path and work as is, but if not enter
# full path here, if unsure open a terminal and type 'where subliminal'
#subliminal="subliminal"    

# See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for language codes
# and https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes for 3 letter (optsubcode1b) codes.
# You can use either, but the 2 letter codes (optsubcode1a) are more common.
#osubname1="forced"
#osubcode1a="en"
#osubcode1b="eng"
#osubname2="English"
#osubcode2a="en"
#osubcode2b="eng"

# Logins for Subtitle providers. Fee free to use them, but the plugin will work without them,
# but you may have to wait longer for results and some providers may not be available.
#opts.addict7edUser=""
#opts.addict7edPass=""
#opts.legendastvUser=""
#opts.legendastvPass=""
#opts.opensubtitlesUser=""
#opts.opensubtitlesPass=""
#opts.subscenterUser=""
#opts.subscenterPass=""