# UNCOMMENT AND SET enabled=no to disable this plugin
#enabled=yes
# path to subliminal, should be in your path and work as is, but if not enter
# full path here, if unsure open a terminal and type 'where subliminal'
#subliminal=subliminal

# See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for language codes
# and https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes for 3 letter (optsubcode1b) codes.
# You can use either, but the 2 letter codes (optsubcode1a) are more common.
#osubname1=forced
#osubcode1a=en
#osubcode1b=eng
#osubname2=English
#osubcode2a=en
#osubcode2b=eng

# Logins for Subtitle providers. Fee free to use them, but the plugin will work without them,
# but you may have to wait longer for results and some providers may not be available.
#opts.addict7edUser=user
#opts.addict7edPass=pass
#opts.legendastvUser=user
#opts.legendastvPass=pass
#opts.opensubtitlesUser=user
#opts.opensubtitlesPass=pass
#opts.subscenterUser=user
#opts.subscenterPass=pass

# Button colours for manual search
#manualsearch_searchcolor=&H00C800&
#manualsearch_cancelcolor=&H0000FF&

# Configurable values for size and position of manual search box
# Horizontal position of box CENTER, 0-1 (fraction of screen width)
#prompt_x=0.5
# Vertical position of box TOP edge, 0-1 (fraction of screen height)
#prompt_y=0.15
#prompt_width=640
#prompt_height=76
#prompt_corner_radius=8
#prompt_fill_color=&H262626&
#prompt_fill_alpha=40
#prompt_border_color=&H0A0A0A&
#prompt_border_alpha=00
#prompt_border_width=2
#prompt_text_color=&HFFFFFF&
#prompt_label_color=&HAAAAAA&
#prompt_font_size=30