#enabled=yes
# Path to subliminal executable {browse}
#subliminal=subliminal
# Text name of first subtitle preference {text}
#osubname1=forced
# Two letter code of first subtitle preference {text}
#osubcode1a=en
# Three letter code of first subtitle preference {text}
#osubcode1b=eng
# Text name of second subtitle preference {text}
#osubname2=English
# Two letter code of second subtitle preference {text}
#osubcode2a=en
# Three letter code of second subtitle preference {text}
#osubcode2b=eng
# addict7ed username {text}
#opts.addict7edUser=user
# addict7ed password {text}
#opts.addict7edPass=pass
# legendastv username {text}
#opts.legendastvUser=user
# legendastv password {text}
#opts.legendastvPass=pass
# opensubtitles username {text}
#opts.opensubtitlesUser=user
# opensubtitles password {text}
#opts.opensubtitlesPass=pass
# subscenter username {text}
#opts.subscenterUser=user
# subscenter password {text}
#opts.subscenterPass=pass

# Colour for manual search button {colourpicker}
#manualsearch_searchcolor=&H00C800&
# Color for manual search cancel button {colourpicker}
#manualsearch_cancelcolor=&H0000FF&
#prompt_x=0.5
# Vertical position manual search prompt from top (0) to bottom (1) of window {float(0.0-1.0)}
#prompt_y=0.15
# Manual search prompt width (px) {int(100-1920)}
#prompt_width=640
# Manual search prompt height (px) {int(50-1080)}
#prompt_height=76
# Manual search prompt corner radius {int(0-30)}
#prompt_corner_radius=8
# Manual search background colour {colourpicker}
#prompt_fill_color=&H262626&
# Manual search background alpha (0-255) {int(0-255)}
#prompt_fill_alpha=40
# Manual search border colour {colourpicker}
#prompt_border_color=&H0A0A0A&
# Manual search border alpha (0-255) {int(0-255)}
#prompt_border_alpha=0
# Manual search border width (px) {int(0-15)}
#prompt_border_width=2
# Manual prompt text colour {colourpicker}
#prompt_text_color=&HFFFFFF&
# Manual prompt label colour {colourpicker}
#prompt_label_color=&HAAAAAA&
# Manual prompt font size {int(10-70)}
#prompt_font_size=30