#enabled=yes
# Dark or Light mode {select:Dark(no),Light(yes)}
#light_mode=no      # when true: white bg, black controls
# Border on main box {bool}
#border=yes         # draw border on main box
# Radius of main box corners {int(0-30)}
#box_radius=10      # corner radius of main box
# Alpha of main box background 0 (opaque) to 255 (fully transparent) {int(0-255)}
#boxalpha=80
# Skip forward left click command {text}
#skip_forward_mbtn_left_command=seek 30
# Skip forward right click command {text}
#skip_forward_mbtn_right_command=seek 60
# Skip forward time middle click command {text}
#skip_forward_mbtn_mid_command=seek 90
# Skip backward left click command {text}
#skip_backward_mbtn_left_command=seek -30
# Skip backward right click command {text}
#skip_backward_mbtn_right_command=seek -60
# Skip backward time middle click command {text}
#skip_backward_mbtn_mid_command=seek -90
