#light_mode=no      # when true: white bg, black controls
#border=yes         # draw border on main box
#box_radius=10      # corner radius of main box
#boxalpha = 80      # alpha of the background box 0 (opaque) to 255 (fully transparent)
