#light_mode=no      # when true: white bg, black controls
#border=yes         # draw border on main box
#box_radius=10      # corner radius of main box
#boxalpha = 80      # alpha of the background box 0 (opaque) to 255 (fully transparent)
#skip_forward_mbtn_left_command=seek 30
#skip_forward_mbtn_right_command=seek 60
#skip_forward_mbtn_mid_command=seek 90
#skip_backward_mbtn_left_command=seek -30
#skip_backward_mbtn_right_command=seek -60
#skip_backward_mbtn_mid_command=seek -90
