#enabled=yes
#path="~~/recent.json"
# Length of recent list {int(5-100)}
length=20
# Width of recent list {int(20-200)}
#width=88
# Ignore same series in recent list {bool}
#ignore_same_series=yes
# Reduce file i/o {bool}
#reduce_io=yes
