#enabled=yes
#socket=""
#thumbnail=""
# Max thumbnail width {int(80-400)}
#max_height=200
# Max thumbnail height {int(80-400)}
#max_width=200
# Scale factor for thumbnail display size {int(1-3)}
#scale_factor=1
# Apply tone-mapping {onoff 1}
#tone_mapping="auto"
#overlay_id=42
#spawn_first=no
#quit_after_inactivity=3
# Enable on network playback {bool}
#network=yes
#audio=no
# Enable hardware decoding {bool}
hwdec=yes
# Use native Windows API to write to pipe (requires LuaJIT) {bool}
direct_io=yes
# Custom path to the mpv executable {browse}
#mpv_path="mpv"