#enabled=yes
# Enable auto-apply of VapourSynth {bool}
#auto_apply=yes
# FPS to apply when auto-apply is enabled. Comma separate the list to set different fps for different resolutions {text}
auto_fps=60,30
# Max resolutions for auto-apply. Comma separate as with auto_fps, each res must have a matching fps {select:720p(1280)|1080p(1920)|4K(3840)|All(#)}
auto_max_res=1920,3840