#enabled=yes
# Enable auto-apply of VapourSynth {bool}
#auto_apply=yes
# FPS to apply when auto-apply is enabled {int(30-480)}
#auto_fps=60
# Max resolution for auto-apply {select:720p(1280)|1080p(1920)|4K(3840)|All(#)}
#auto_max_res=1920