# Enable auto-apply of VapourSynth filter based on resolution
auto-apply=no
# FPS to apply when auto-apply is enabled
auto-fps=60
# Maximum resolution (width) to auto-apply VapourSynth filter, 1920=1080p. If the video width is equal to or less than this value, the filter will be applied automatically.
auto-max-res=1920